name: handson.ai
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - pytorch
    - damianavila82
dependencies:
    - python=3.6
    - numpy #=1.13.*
    - matplotlib #=2.1.*
    - jupyter #=1.0.0
    - pandas #=0.21.*
    # DL related
    - pytorch #=0.3.*
    - torchvision #=0.2.*
    - mkl #=2018.0.*
    - scikit-learn
     # for Jupyter
    - rise #=5.1.*
    - jupyter_contrib_nbextensions #=0.3.3
    - pip:
        # for VS code
        - pylint #==1.8.*
        - autopep8 #==1.3.*