name: handson.ai
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - pytorch
dependencies:
    - python>=3.5.4
    - numpy>=1.13.03
    - matplotlib>=2.1.0
    - jupyter>=1.0.0
    - pandas==0.21.0
    # DL related
    - pytorch>=0.3.0
    - torchvision>=0.2.0
    - mkl>=2018.0.1
    - pip:
        - pylint>=1.7.4 # for VS code
        - autopep8>=1.3.3 # for VS code